services:
  my_app:
    build:
      .
    ports:
      - 4000:4000
    depends_on:
      app_postgres:
        condition: service_healthy
  app_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGLOGGING: "all"
      POSTGRES_DB: todo_app
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    ports:
      - 5432:5432
    volumes:
      - ./infra-config/data/postgres:/var/lib/postgresql/data
      - ./infra-config/postgresql-db-init.sql:/docker-entrypoint-initdb.d/create_database.sql
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./infra-config/loki-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./infra-config/tempo-data:/var/tempo

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo/config.yml" ]
    volumes:
      - ./infra-config/tempo-config.yml:/etc/tempo/config.yml
      - ./infra-config/tempo-data:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "4317" # otlp grpc
    depends_on:
      - init

  grafana:
    image: grafana/grafana:latest

    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - 3000:3000/tcp
    volumes:
      - ./infra-config/grafana:/etc/grafana/provisioning
      - ./infra-config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317" # OTLP gRPC
      - "55681:55681" # OTLP HTTP
    volumes:
      - ./infra-config/otel-config.yml:/etc/otel-config.yml
    command: ["--config=/etc/otel-config.yml"]

volumes:
  grafana-data:


